# Generated by Django 4.1 on 2023-02-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripwire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, null=True)),
                ('host', models.CharField(max_length=100, null=True)),
                ('process', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Tripwire',
            },
        ),
        migrations.CreateModel(
            name='Vsftpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, null=True)),
                ('host', models.CharField(max_length=100, null=True)),
                ('process', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Vsftpd',
            },
        ),
    ]
